import type { Edge } from "@xyflow/react";

import type {
  AmplifyGraphNode,
  AmplifyWorkspace,
  SplitNodeType,
  StrategyNodeType,
} from "./types";
import { amplifySuggestions } from "./catalog";

const mainEdgeStyle = { stroke: "#61B3CF", strokeWidth: 2 };

export const amplifyExampleNodes: AmplifyGraphNode[] = [
  {
    id: "marinade",
    type: "strategy",
    position: { x: 80, y: 340 },
    data: {
      nodeKind: "strategy",
      title: "Marinade stake",
      summary: "Stake SOL into liquid staking before routing the position downstream.",
      protocol: "Marinade",
      action: "Stake SOL",
      inputAsset: "SOL",
      acceptedAssets: ["SOL"],
      outputs: [
        {
          id: "next",
          label: "Staked position",
          asset: "mSOL",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "81.2 mSOL",
        },
        {
          id: "rewards",
          label: "Reward stream",
          asset: "MNDE rewards",
          kind: "reward",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "12.4 MNDE",
          cadenceLabel: "Weekly",
        },
      ],
      status: "active",
      holdingsLabel: "81.2 mSOL on Marinade",
      platformLink: {
        label: "View on Marinade",
        href: "https://marinade.finance",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "81.2 mSOL",
        updatedAtLabel: "Updated 2h ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "7.5%",
      apyType: "earn",
      collectInterval: "Weekly",
    },
  } satisfies StrategyNodeType,
  {
    id: "split",
    type: "split",
    position: { x: 580, y: 350 },
    data: {
      nodeKind: "split",
      title: "mSOL split",
      summary: "Route the staked position across borrow and lend branches.",
      status: "active",
      acceptedAssets: ["mSOL"],
      outputs: [
        {
          id: "a",
          label: "Path A",
          asset: "50% mSOL",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "40.6 mSOL",
        },
        {
          id: "b",
          label: "Path B",
          asset: "50% mSOL",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "40.6 mSOL",
        },
      ],
      holdingsLabel: "81.2 mSOL routed",
      activeSnapshot: {
        status: "active",
        amountLabel: "81.2 mSOL",
        updatedAtLabel: "Updated 2h ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      splitA: 50,
      splitB: 50,
      asset: "mSOL",
    },
  } satisfies SplitNodeType,
  {
    id: "kamino",
    type: "strategy",
    position: { x: 1080, y: 140 },
    data: {
      nodeKind: "strategy",
      title: "Kamino supply and borrow",
      summary: "Use mSOL as collateral and borrow USDC for the next loop branch.",
      protocol: "Kamino",
      action: "Supply & Borrow",
      inputAsset: "mSOL",
      acceptedAssets: ["mSOL"],
      outputs: [
        {
          id: "next",
          label: "Borrowed USDC",
          asset: "USDC",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "23,800 USDC",
        },
      ],
      status: "active",
      holdingsLabel: "40.6 mSOL collateralised",
      platformLink: {
        label: "View on Kamino",
        href: "https://app.kamino.finance",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "23,800 USDC borrowed",
        updatedAtLabel: "Updated 1h ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "3.2%",
      apyType: "cost",
    },
  } satisfies StrategyNodeType,
  {
    id: "split-usdc",
    type: "split",
    position: { x: 1580, y: 150 },
    data: {
      nodeKind: "split",
      title: "USDC split",
      summary: "Divide borrowed stablecoin across LP and lending branches.",
      status: "active",
      acceptedAssets: ["USDC"],
      outputs: [
        {
          id: "a",
          label: "Path A",
          asset: "30% USDC",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "7,140 USDC",
        },
        {
          id: "b",
          label: "Path B",
          asset: "70% USDC",
          kind: "primary",
          compatibleNodeTypes: ["amount", "strategy", "split", "destination"],
          amountLabel: "16,660 USDC",
        },
      ],
      holdingsLabel: "23,800 USDC routed",
      activeSnapshot: {
        status: "active",
        amountLabel: "23,800 USDC",
        updatedAtLabel: "Updated 1h ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      splitA: 30,
      splitB: 70,
      asset: "USDC",
    },
  } satisfies SplitNodeType,
  {
    id: "raydium",
    type: "strategy",
    position: { x: 2080, y: 20 },
    data: {
      nodeKind: "strategy",
      title: "Raydium liquidity leg",
      summary: "Deploy part of the borrowed stablecoin into a higher-yield LP branch.",
      protocol: "Raydium",
      action: "Provide Liquidity",
      inputAsset: "USDC",
      acceptedAssets: ["USDC"],
      outputs: [
        {
          id: "next",
          label: "LP fee stream",
          asset: "LP Fees",
          kind: "primary",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "$824 / month",
        },
        {
          id: "rewards",
          label: "Harvest output",
          asset: "RAY rewards",
          kind: "reward",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "146 RAY",
          cadenceLabel: "Weekly",
        },
      ],
      status: "active",
      holdingsLabel: "7,140 USDC deployed",
      platformLink: {
        label: "View on Raydium",
        href: "https://raydium.io",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "7,140 USDC",
        updatedAtLabel: "Updated 40m ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "12.0%",
      apyType: "earn",
      collectInterval: "Weekly",
    },
  } satisfies StrategyNodeType,
  {
    id: "marginfi",
    type: "strategy",
    position: { x: 2080, y: 500 },
    data: {
      nodeKind: "strategy",
      title: "Marginfi lend leg",
      summary: "Park the remaining stablecoin in a lower-volatility lending branch.",
      protocol: "Marginfi",
      action: "Lend USDC",
      inputAsset: "USDC",
      acceptedAssets: ["USDC"],
      outputs: [
        {
          id: "next",
          label: "Interest stream",
          asset: "Interest",
          kind: "primary",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "$116 / month",
        },
        {
          id: "rewards",
          label: "Lending rewards",
          asset: "MRGN rewards",
          kind: "reward",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "88 MRGN",
          cadenceLabel: "Monthly",
        },
      ],
      status: "active",
      holdingsLabel: "16,660 USDC supplied",
      platformLink: {
        label: "View on Marginfi",
        href: "https://marginfi.com",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "16,660 USDC",
        updatedAtLabel: "Updated 40m ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "8.4%",
      apyType: "earn",
      collectInterval: "Monthly",
    },
  } satisfies StrategyNodeType,
  {
    id: "drift",
    type: "strategy",
    position: { x: 1080, y: 760 },
    data: {
      nodeKind: "strategy",
      title: "Drift lend leg",
      summary: "Lend the second mSOL branch while keeping a yield stream available for reinvestment.",
      protocol: "Drift",
      action: "Lend mSOL",
      inputAsset: "mSOL",
      acceptedAssets: ["mSOL"],
      outputs: [
        {
          id: "next",
          label: "Yield stream",
          asset: "mSOL yield",
          kind: "primary",
          compatibleNodeTypes: ["reward", "split", "destination", "strategy"],
          amountLabel: "2.11 mSOL / month",
        },
        {
          id: "rewards",
          label: "Interest route",
          asset: "Interest",
          kind: "reward",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "$92 / month",
          cadenceLabel: "Monthly",
        },
      ],
      status: "active",
      holdingsLabel: "40.6 mSOL supplied",
      platformLink: {
        label: "View on Drift",
        href: "https://www.drift.trade",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "40.6 mSOL",
        updatedAtLabel: "Updated 55m ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "5.2%",
      apyType: "earn",
      collectInterval: "Monthly",
    },
  } satisfies StrategyNodeType,
  {
    id: "orca",
    type: "strategy",
    position: { x: 1580, y: 760 },
    data: {
      nodeKind: "strategy",
      title: "Orca concentrated LP",
      summary: "Route Drift yield into a more aggressive mSOL LP branch.",
      protocol: "Orca",
      action: "Concentrated LP",
      inputAsset: "mSOL yield",
      acceptedAssets: ["mSOL yield", "mSOL"],
      outputs: [
        {
          id: "next",
          label: "LP fee stream",
          asset: "LP Fees",
          kind: "primary",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "$148 / month",
        },
        {
          id: "rewards",
          label: "LP rewards",
          asset: "ORCA rewards",
          kind: "reward",
          compatibleNodeTypes: ["reward", "split", "destination"],
          amountLabel: "34 ORCA",
          cadenceLabel: "Bi-weekly",
        },
      ],
      status: "active",
      holdingsLabel: "2.11 mSOL yield recycled",
      platformLink: {
        label: "View on Orca",
        href: "https://www.orca.so",
      },
      activeSnapshot: {
        status: "active",
        amountLabel: "2.11 mSOL",
        updatedAtLabel: "Updated 20m ago",
      },
      draftState: {
        hasChanges: false,
        changedFields: [],
      },
      apy: "9.1%",
      apyType: "earn",
      collectInterval: "Bi-weekly",
    },
  } satisfies StrategyNodeType,
];

export const amplifyExampleEdges: Edge<{ asset: string }>[] = [
  {
    id: "e-marinade-split",
    source: "marinade",
    sourceHandle: "next",
    target: "split",
    type: "asset",
    data: { asset: "mSOL" },
    style: mainEdgeStyle,
    animated: true,
  },
  {
    id: "e-split-kamino",
    source: "split",
    sourceHandle: "a",
    target: "kamino",
    type: "asset",
    data: { asset: "50% mSOL" },
    style: mainEdgeStyle,
    animated: true,
  },
  {
    id: "e-split-drift",
    source: "split",
    sourceHandle: "b",
    target: "drift",
    type: "asset",
    data: { asset: "50% mSOL" },
    style: { ...mainEdgeStyle, stroke: "#34d399" },
    animated: true,
  },
  {
    id: "e-kamino-split-usdc",
    source: "kamino",
    sourceHandle: "next",
    target: "split-usdc",
    type: "asset",
    data: { asset: "USDC" },
    style: mainEdgeStyle,
    animated: true,
  },
  {
    id: "e-split-usdc-raydium",
    source: "split-usdc",
    sourceHandle: "a",
    target: "raydium",
    type: "asset",
    data: { asset: "30% USDC" },
    style: mainEdgeStyle,
    animated: true,
  },
  {
    id: "e-split-usdc-marginfi",
    source: "split-usdc",
    sourceHandle: "b",
    target: "marginfi",
    type: "asset",
    data: { asset: "70% USDC" },
    style: mainEdgeStyle,
    animated: true,
  },
  {
    id: "e-drift-orca",
    source: "drift",
    sourceHandle: "next",
    target: "orca",
    type: "asset",
    data: { asset: "mSOL yield" },
    style: { ...mainEdgeStyle, stroke: "#34d399" },
    animated: true,
  },
];

export const amplifyExampleWorkspace: AmplifyWorkspace = {
  id: "amplify-sol-yield-loop",
  name: "SOL Yield Loop",
  summary:
    "A composable SOL yield loop that moves across staking, borrowing, and LP positions.",
  kind: "example",
  isEditable: false,
  executionState: "active",
  activeSnapshot: {
    updatedAtLabel: "Last simulated today",
    nodeIds: amplifyExampleNodes.map((node) => node.id),
  },
  draftState: {
    updatedAtLabel: "No draft changes",
    changedNodeIds: [],
    impactedNodeIds: [],
  },
  activeThreadId: "amplify-thread-loop-optimisation",
  threads: [
    {
      id: "amplify-thread-loop-optimisation",
      title: "Loop optimisation",
      preview: "Refining the current loop and comparing alternatives to Raydium.",
      lastViewedLabel: "Last viewed today",
      messages: [
        {
          id: "amplify-thread-loop-optimisation-ai-1",
          role: "ai",
          content:
            "Welcome to Tidal Amplify. I can help you build and optimise yield strategies across Solana protocols.",
        },
        {
          id: "amplify-thread-loop-optimisation-user-1",
          role: "user",
          content:
            "Can you help me improve the yield on this loop? I'd like to explore alternatives to Raydium for the liquidity step.",
        },
        {
          id: "amplify-thread-loop-optimisation-ai-2",
          role: "ai",
          content:
            "This strategy stakes SOL through Marinade, borrows USDC on Kamino, and provides liquidity on Raydium for a net estimated yield of ~16.3%.",
        },
      ],
    },
    {
      id: "amplify-thread-risk-review",
      title: "Risk review",
      preview: "Pressure-testing where the current loop is most exposed.",
      lastViewedLabel: "Last viewed yesterday",
      messages: [
        {
          id: "amplify-thread-risk-review-ai-1",
          role: "ai",
          content:
            "The main risk concentrations are Kamino borrow cost sensitivity and the LP leg on Raydium.",
        },
        {
          id: "amplify-thread-risk-review-user-1",
          role: "user",
          content:
            "Break down which step in the loop contributes most of the risk and where the yield could compress fastest.",
        },
      ],
    },
  ],
  suggestions: amplifySuggestions,
  nodes: amplifyExampleNodes,
  edges: amplifyExampleEdges,
};
